 {{- if .Values.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.appName }}
      containers:
        - name: schema-loader
          image: 115099330984.dkr.ecr.us-east-1.amazonaws.com/schema-loader:latest
          imagePullPolicy: Always
          env:
            - name: COMPONENT
              value: {{ .Values.appName }}
      restartPolicy: Never
  backoffLimit: 4
   {{- end }}
   {{ - end }}