{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::115099330984:role/eks-ssm-ps-prod-role
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}